- name: Log into registry
  docker_login:
    registry: "{{ docker_registry_url }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    email: "{{ docker_registry_username_email }}"
    reauthorize: "{{ docker_regisry_reauth | default('yes') }}"
