---

- name: swarm directory present
  file:
    path: "{{ stack_directory }}"
    state: directory
    owner: "{{ swarm_user | default('root') }}"
    group: "{{ swarm_group | default('root') }}"
    mode: "0700"


- name: create swarm template
  template:
    src: "{{ docker_compose_template }}"
    dest: "{{ stack_directory }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0600

- name: copy configs if they exist
  copy:
    src: files
    dest: "{{ stack_directory }}"
    owner: root
    group: root
    mode: 0600
  when: swarm_copy_files | default(false)
