---

- name: create swarm template
  template:
    src: "{{ docker_compose_template }}"
    dest: "{{ stack_directory }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0600

- name: copy configs if they exist
  copy:
    source: files
    dest: "{{ stack_directory }}/files"
    owner: root
    group: root
    mode: 0600
  when: swarm_config_dir is defined
