---

- name: make sure that directory exists
  file:
    path: "{{ swarm_base_dir | default('/etc/docker/compose/')}}"
    state: directory
    mode: 0700
    owner: root
    group: root

- name: clone swarm compose files
  git:
    repo: "{{ swarm_git_repo  }}"
    ssh_opts: "-o StrictHostKeyChecking=no"
    dest:  "{{ swarm_base_dir | default('/etc/docker/compose/') }}"
    version: "{{ branch_name }}"

- name: deploy stack with registry password
  command: >
    retry=5
    i=1;
    docker login --username="{{ docker_registry_user }}" --password="{{ docker_registry_password }}" "{{ docker_registry_url }}"
    while [[ $i -lt $retry ]]; do
      docker stack deploy --compose-file --with-registry-auth docker-compose.yml "{{ stack_name }}";
      ret=$?;
      if [[ $ret -eq 0 ]]; then echo 'Stack created'; break;
      else
        echo "Stack creation failed, retrying in 3 seconds.." >&2;
        sleep 3;
        i=$(( i + 1 ));
      fi;
      if [[ $i -ge $retry ]]; then
        echo "Stack creation failed!"; exit 1;
      fi;
    done;
  args:
    chdir: "{{ swarm_base_dir | default('/etc/docker/compose/') + swarm_dir|default('swarm/') + stack_name }}"
  when: docker_registry_password_auth | default(true)

- name: deploy stack without registry password
  command: >
    retry=5
    i=1;
    while [[ $i -lt $retry ]]; do
      docker stack deploy --compose-file docker-compose.yml "{{ stack_name }}";
      ret=$?;
      if [[ $ret -eq 0 ]]; then echo 'Stack created'; break;
      else
        echo "Stack creation failed, retrying in 3 seconds.." >&2;
        sleep 3;
        i=$(( i + 1 ));
      fi;
      if [[ $i -ge $retry ]]; then
        echo "Stack creation failed!"; exit 1;
      fi;
    done;
  args:
    chdir: "{{ swarm_base_dir | default('/etc/docker/compose/') + swarm_dir|default('swarm/') + stack_name }}"
  when: not docker_registry_password_auth | default(true)
